accent = "#bd00ff"
cursor = "#ff2a6d"
foreground = "#c792ff"
background = "#120621"
selection_foreground = "#120621"
selection_background = "#bd00ff"

color0 = "#241633"
color1 = "#ff2a6d"
color2 = "#05ffa1"
color3 = "#fee440"
color4 = "#00b8ff"
color5 = "#bd00ff"
color6 = "#00f0ff"
color7 = "#c792ff"
color8 = "#4b3a63"
color9 = "#ff5c8a"
color10 = "#6bffc8"
color11 = "#fffba0"
color12 = "#5ccfff"
color13 = "#d580ff"
color14 = "#7dfcff"
color15 = "#eddcff"
