$color = rgba(18, 6, 33, 1)
$inner_color = rgba(18, 6, 33, 0.66)
$outer_color = rgba(157, 78, 221, 1)
$font_color = rgba(199, 146, 255, 1)
$placeholder_color = rgba(199, 146, 255, 0.7)
$check_color = rgba(189, 0, 255, 1)
